### ISSUE TITLE
tags for stable versions

### ISSUE THREAD

**Issue by afazleev** [IlyaNavodkin/BIDTP-dotnet#5]
please tag commits for stable versions or make releases

**Comment by IlyaNavodkin** [comment]
Okay, I'll do it soon

**Comment by IlyaNavodkin** [comment]
> please tag commits for stable versions or make releases
While the latest version is always available on nuget
https://www.nuget.org/packages/BIDTP.Dotnet.Core

**Comment by IlyaNavodkin** [comment]
https://github.com/IlyaNavodkin/BIDTP-dotnet/releases/tag/2.0.0

Done
